name: mainline
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "The SHA1 key of the commit that triggered this job is $(git rev-parse --short HEAD)"
