name: mainline
on:
  push:
    branches: 
      - '**/issue**'

env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mainline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The SHA1 key of the commit that triggered this job is $(git rev-parse --short HEAD)"
    
  verify_issue:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.id }}
